### ISSUE TITLE
Search params impact search after navigating away from page

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#81]
When I set filter parameters on the transfer or search page
And I navigate away from the page 
And I come back to the page
And I change any filter
Then the previous search filters impact the new search <-- *This shouldn't happen*

Here is a video:
![filter_issue](https://cloud.githubusercontent.com/assets/17623856/25835445/d8f9fac8-344c-11e7-91df-d2f0d58f05bb.gif)

**Comment by Jbcampbe** [comment]
@amenders @ekraihan this bug is a consequence of some of our loose coupling issues between UI and data : ) It can most definitely be fixed but if we want it fixed correctly then we may end up refactoring a large portion of the transfer and search page code.... Do we want to do that for `Release 2.1.0` or maybe save it for 3.0.0.... or maybe we need a 2.2.0?

**Comment by amenders** [comment]
This is much like the cart persistence to me. I would say that this is a serious bug for software that we want to bill as prod-ready. :P

**Comment by ekraihan** [comment]
Maybe it would be as easy to fix as cart persistence?!?!?!?!? 😁 😬 😁
